version: '3.3'

services:
  db_mysql:
    image: mysql:5.7
    restart: always
    env_file: .env  # Indica el archivo que contiene las variables de entorno
    ports:
      - '3306:3306'
    container_name: mysql_db
    volumes:
      - my-db:/var/lib/mysql

# Define el volumen
volumes:
  my-db: