# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - TZ=America/Mexico_City
      - PGTZ=America/Mexico_City
      - POSTGRES_USER=cbonilla
      - POSTGRES_DB=contracargos
      - POSTGRES_PASSWORD=Banwire1234
    ports:
      - "5432:5432"
    container_name: contracargos_db
